using DMAdvantage.Shared.Enums;

namespace DMAdvantage.Shared
{
    public static class StaticData
    {
        public static Dictionary<WeaponProperty, string> WeaponPropertyDescriptions = new()
        {
            { WeaponProperty.Ammunition, "You can use a weapon that has the ammunition property to make a ranged attack only if you have ammunition to fire from the weapon. Each time you attack with the weapon, you expend one piece of ammunition. If you use a weapon that has the ammunition property to make a melee attack, you treat the weapon as an improvised weapon." },
            { WeaponProperty.Auto, "Automatic weapons can only fire in burst or rapid modes. If the weapon has both burst and rapid properties, you choose which mode to use. You can only use one mode at a time." },
            { WeaponProperty.Brutal, "When you score a critical hit with a weapon with the brutal property, you roll a number of additional weapon damage dice equal to the brutal number." },
            { WeaponProperty.Burst, "When you would make a ranged weapon attack with a weapon with the burst property, you can instead spray a 10-foot-cube area within range with shots, consuming ammunition equal to the burst number. Each creature in the area must make a Dexterity saving throw (DC = 8 + your bonus to attacks with the weapon) or take the weapon’s normal damage. If the targeted area is beyond normal range but within long range, affected targets have advantage on the save." },
            { WeaponProperty.Defensive, "When you make your first attack on your turn with a weapon with the defensive property, you can choose to suffer a penalty to attack and damage rolls with that weapon up to the defensive number. If you do so, you gain the same bonus to AC. These effects last until the start of your next turn, as long as you’re holding the weapon." },
            { WeaponProperty.Dexterity, "A weapon with this special property requires more skill to control. While wielding it, you have disadvantage on attack rolls unless you meet the Dexterity requirement." },
            { WeaponProperty.Dire, "Before you make a weapon attack with a weapon with the dire property, you can choose to suffer a penalty to the attack roll up to the dire number. If you do so and you hit with it, you gain the same bonus to the damage roll." },
            { WeaponProperty.Disarming, "When you score a critical hit with a weapon with the disarming property against a creature that is holding an object, you can attempt to disarm the target (no action required). If the target is no more than one size larger than you (your size or smaller if your weapon has the light property), it must succeed on a Strength saving throw (DC = 8 + your bonus to attacks with the weapon) or it drops an object of your choice at its feet." },
            { WeaponProperty.Disguised, "You have advantage on Charisma (Deception) checks made to hide the nature of a disguised weapon." },
            { WeaponProperty.Disintegrate, "When a creature is reduced to 0 hit points by a weapon with the disintegrate property, it must make a Constitution saving throw, DC equal to the disintegrate number. On a failed save, it dies immediately without making death saving throws. A disintegrated creature and everything unenhanced it is wearing or carrying are reduced to a pile of fine gray dust. A creature destroyed in this way can not be revitalized." },
            { WeaponProperty.Disruptive, "When a creature is forced to make a Constitution saving throw to maintain concentration due to taking damage from a weapon with the disruptive property, the DC for the check equals 10 or the full damage taken, whichever number is higher, instead of only half." },
            { WeaponProperty.Double, "This weapon can be used with one or two hands. A damage value in parentheses appears with the property-the damage when the weapon is used with Double-Weapon Fighting. See the rules for Double-Weapon Fighting in chapter 9." },
            { WeaponProperty.Finesse, "When making an attack with a finesse weapon, you use your choice of your Strength or Dexterity modifier for the attack and damage rolls. You must use the same modifier for both rolls." },
            { WeaponProperty.Fixed, "A weapon with the fixed property does not fill the hand, but you can’t use the weapon while the hand is full. Additionally, you have a +10 bonus to ability checks and saving throws to avoid being disarmed of this weapon." },
            { WeaponProperty.Heavy, "When you hit with an attack roll using Strength with this weapon, you deal additional damage equal to half your Strength modifier (rounded up, minimum of +1)." },
            { WeaponProperty.Hidden, "You have advantage on Dexterity (Sleight of Hand) checks made to conceal a hidden weapon." },
            { WeaponProperty.Keen, "When you make a weapon attack with a weapon with the keen property, the critical hit range increases by an amount equal to the keen number." },
            { WeaponProperty.Light, "A light weapon is small and easy to handle, making it ideal for use when engaging in Double- or Two-Weapon Fighting. See the rules for Double- and Two-Weapon Fighting in chapter 9." },
            { WeaponProperty.Luminous, "A weapon with the luminous property sheds dim light in a 5-foot radius while activated. Additionally, Dexterity (Stealth) checks made while the weapon is activated have disadvantage." },
            { WeaponProperty.Mighty, "When making an attack with a mighty weapon, you use your choice of your Strength or Dexterity modifier for the attack and damage rolls. You must use the same modifier for both rolls." },
            { WeaponProperty.Neuralizing, "When you hit a creature with a weapon with the neuralizing property, you can force it to make a Wisdom saving throw, DC equal to the neuralizing number. On a failed save, the creature takes an additional 1d4 psychic damage and becomes frightened of you until the start of its next turn." },
            { WeaponProperty.Piercing, "Before you make a weapon attack with a weapon with the piercing property, you can choose to suffer a penalty to the attack roll up to the piercing number. If you do so, you gain the same bonus to the next attack roll you make against the same target before the start of your next turn." },
            { WeaponProperty.Range, "A weapon that can be used to make a ranged attack has a range shown in parentheses after the ammunition or thrown property. The range lists two numbers. The first is the weapon’s normal range in feet, and the second indicates the weapon’s maximum range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can’t attack a target beyond the weapon’s long range." },
            { WeaponProperty.Rapid, "When you would make a ranged weapon attack with a weapon with the rapid property, you can instead unload on a single target, consuming ammunition equal to the rapid number. The target must make a Dexterity saving throw (DC = 8 + your bonus to attacks with the weapon). On a failed save, roll the weapon’s damage dice twice and add them together, adding relevant modifiers as normal. If the target is beyond normal range but within long range, it has advantage on the save." },
            { WeaponProperty.Reach, "This weapon adds 5 feet to your reach with it." },
            { WeaponProperty.Reload, "A limited number of shots can be made with a weapon that has the reload property. A character must then reload it using an action or a bonus action (the character’s choice). You must have one free hand to reload." },
            { WeaponProperty.Returning, "When you throw a weapon with the returning property, it automatically returns to your hand after the attack is complete, whether you hit or miss." },
            { WeaponProperty.Shocking, "When you hit a creature with a weapon with the shocking property, you can force it to make a Dexterity saving throw, DC equal to the shocking number. On a failed save, the creature takes an additional 1d4 lightning damage and becomes shocked until the end of its next turn." },
            { WeaponProperty.Silent, "When you make a ranged attack with a weapon with the silent property while hidden, it does not automatically reveal your presence. Make a Dexterity (Stealth) check contested by your targets’ Wisdom (Perception) check. On a success, you remain hidden." },
            { WeaponProperty.Sonorous, "When you hit a creature with a weapon with the sonorous property, you can force it to make a Constitution saving throw, DC equal to the sonorous number. On a failed save, the creature takes an additional 1d4 sonic damage and becomes deafened until the end of its next turn." },
            { WeaponProperty.Special, "A weapon with the special property has unusual rules governing its use, explained in the weapon’s description (see “Special Weapons” later in this section)." },
            { WeaponProperty.Strength, "A weapon with this special property has a heavy kickback. While wielding it, you have disadvantage on attack rolls unless you meet the Strength requirement. If the weapon has the burst or rapid property, you must meet the Strength requirement to use this feature." },
            { WeaponProperty.Switch, "A weapon with the switch property can deal an alternate type of damage. A damage value appears in parentheses appears with the property-the damage when the weapon uses its alternate damage type. On your turn, you can use your object interaction to change the weapon’s damage type." },
            { WeaponProperty.Thrown, "If a weapon has the thrown property, you can throw the weapon to make a ranged attack. If the weapon is a melee weapon, you use the same ability modifier for that attack roll and damage roll that you would use for a melee attack with the weapon." },
            { WeaponProperty.TwoHanded, "This weapon requires two hands to use." },
            { WeaponProperty.Versatile, "This weapon can be used with one or two hands. A damage value in parentheses appears with the property-the damage when the weapon is used with two hands to make a melee attack." },
            { WeaponProperty.Vicious,"Whenever you deal damage with a weapon with the vicious property and roll the maximum on a weapon damage die, you gain a bonus to damage equal to the vicious number." },
        };
    }
}
