using Microsoft.AspNetCore.Components;

namespace DMAdvantage.Client.Shared
{
    public partial class ShipActionGrid
    {
        private Dictionary<string, string> _actions = new()
        {
            { "ATTACK RUN", "When you move at least 150 feet towards a target, you may declare an attack run as an action. You must have a clear path towards your target, and nothing should hinder your path (such as difficult terrain or obstacles). If you finish this movement within range of your target, you may use your action to follow it with one of these options: Fire. You may make a single ship weapon attack from a forward-facing limited arc without suffering the normal disadvantage. If you attack with a tertiary or quartenary weapon, the attack deals additional damage equal to the distance of your attack run divided by 50, up to your ship’s Strength modifier (minimum of 1). Ram. You may make a Ram attempt with advantage on your Strength (Ram) check. If you succeed, the target ship takes additional damage equal to the distance of your attack run divided by 50, up to your ship’s Constitution modifier (minimum of +1), or is damaged as normal and becomes stunned until the end of its next turn. Only a deployed pilot can take the Attack Run action." },
            { "BOOST ENGINES", "You can attempt to boost your speed. When you take the Boost Engines action, you make a DC 12 Strength (Boost) check. On a success you increase your speed by 50 until the end of your ship’s next turn." },
            { "BOOST SHIELDS", "You can attempt to boost your shields. When you take the Boost Shields action, you make a Strength (Boost) check DC. On a success, you roll a shield die, without expending it, and gain temporary shield points equal to the result that last until the start of your ship’s next turn." },
            { "BOOST WEAPONS", "You can attempt to boost your weapon output. When you take the Boost Weapons action, the next time this turn your ship deals damage, you make a DC 12 Strength (Boost) check. On a success, you have advantage on the damage roll." },
            { "CAST A POWER", "As normal, you can cast force or tech powers. You cannot target a hostile creature with a power unless you are aware of their presence and location. The Cast a Power action can be taken multiple times on a ship’s turn." },
            { "DIRECT", "When you take the Direct action, one creature can see or hear you gains advantage on the next ability check it makes to perform the task you are helping with, provided that it makes the check before the start of your next turn. Alternatively, you can direct a friendly creature that can hear you in attacking another target. If your ally attacks the target before the start of your next turn, the first attack roll is made with advantage. The Direct action can be taken multiple times on a ship’s turn." },
            { "DOGFIGHT", "When you take the Dogfight action, you engage an enemy, ducking and weaving, vying for a good shot while avoiding theirs. You choose a target you can see and make an opposed Dexterity (Maneuver) check. On a success, you cause the next attack made against your ship by the target to suffer from disadvantage, but you grant the next attack made against your ship by a different target advantage. Additionally, you can perform a primary or tertiary weapon attack from a forward-facing limited firing arc against that ship without suffering the normal disadvantage. Only a deployed pilot can take the Dogfight action." },
            { "EVADE", "When you take the Evade action, you focus entirely on avoiding attacks. Until the start of your next turn, any Attack roll made against has disadvantage if you can see the attacker on your instruments, and you make Dexterity Saving Throws with advantage. This action affects your entire ship: any skill check or attack roll made by your ship or anyone on it also has disadvantage until the end of your ship’s next turn. The effects of Evade end if you are Incapacitated or if your speed drops to 0. Only a deployed pilot can take the Evade action." },
            { "FIRE", "The most common action to take in combat is the Fire action. With this action, you can make an attack (or attacks) with one ship weapon you can reach. See the “Making an Attack” section for the rules that govern attacks. The attack action may be taken multiple times on a ship’s turn, but normally only once per weapon. A pilot taking the attack action attacks at disadvantage." },
            { "FLY", "When you take the Fly action, you gain extra Movement for the current turn. The increase equals your speed, after applying any modifiers. With a speed of 300 feet, for example, your ship can move up to 600 feet on its turn if you Fly. Any increase or decrease to your speed changes this additional Movement by the same amount. If your ship’s speed of 300 feet is reduced to 150 feet, for instance, your ship can move up to 300 feet this turn if you Fly. This action affects your entire ship: any skill check or attack roll made by your ship or anyone on it also has disadvantage until the end of your ship’s next turn. Only a deployed pilot can take the Fly action." },
            { "HARASS", "You can harass an enemy and lock them into a series of close-combat maneuvers in order to prevent their escape. When you take the Harass action, make a contested Dexterity (Maneuver) check against a target within one size category of you and within normal range of at least one of your forward-facing primary weapons. This weapon cannot be used for a Fire action this turn. On a success, if the target voluntarily leaves its square before the beginning of your next turn, it takes damage as though it suffered a critical hit with the primary weapon used to harass. Only a deployed pilot can take the Harass action." },
            { "HIDE", "When you take the Hide action, you make a Dexterity (Hide) check in an attempt to hide your ship, following the rules in chapter 7 for hiding. If you succeed, you gain certain benefits, as described in the “Unseen Attackers and Targets” section later in this chapter. Only a deployed pilot can take the Hide action." },
            { "INTERFERE", "You can attempt to interfere with another creature within 1,000 feet that is deployed on a ship, if you are aware of their presence and location, in the attempt of a task. When you take the Interfere action, you make a Charisma (Interfere) check contested by the target’s Wisdom (Scan) check. If you succeed, the subject has disadvantage on the next ability check or attack roll it makes before the start of your next turn. The Interfere action can be taken multiple times on a ship’s turn." },
            { "PATCH", "You can attempt to have the ship patch up damage it has taken, using one of its Hull Dice. When you take the Patch action, you make a Constitution (Patch) check (DC = 10 or half the ship’s missing hull points, whichever number is higher). On a failure, you have disadvantage on the Hull Dice roll. On a success you roll the Hull Die normally. When you would make a Constitution (Patch) check, you may instead make an Intelligence (Mechanic’s Kit) check at disadvantage. The Patch action can be taken multiple times on a ship’s turn." },
            { "RAM", "You can attempt to ram another ship while flying through its space. When you take the ram action, you make a Strength (Ram) check opposed by the target’s Dexterity (Maneuvering) check. On a failed check the ramming action fails. On a success, both you and the target ship take kinetic damage equal to two of your ship’s Hull Dice + your ship’s Strength modifier. If your ship has shield points remaining, your ship instead takes half this damage. Only a deployed pilot can take the Ram action." },
            { "READY", "Sometimes you want to get the jump on a foe or wait for a particular circumstance before you act. To do so, you can take the Ready action on your turn so that you can act later in the round using your reaction. First, you decide what perceivable circumstance will trigger your reaction.Then, you choose the action you will take in response to that trigger.For instance, 'When the enemy appears, I’ll fire my railgun at it.' When the trigger occurs, you can either take your reaction right after the trigger finishes or ignore the trigger.Remember that you can take only one reaction per round." },
            { "REGENERATE SHIELDS", "You can attempt to regenerate your shields faster, using one of its Shield Dice. When you take the Regenerate Shields action, you make a Strength (Boost) check (DC = 10 or half the ship’s missing shield points, whichever number is higher). On a failure, you roll the Shield Die twice and take the lesser amount. On a success you roll the Shield Die normally." },
            { "SEARCH", "When you take the Search action, you devote your attention to finding something. Depending on the nature of your search, the DM might have you make a Wisdom (Scan) check or an Intelligence (Probe) check." },
            { "USE AN OBJECT", "When an object requires your action for its use, you take the Use an Object action. This action is also useful when you want to interact with more than one object on your turn. The Use an Object action can be taken multiple times on a ship’s turn." }
        };
        [Parameter] public string Title { get; set; }
        private string? _selectedAction;

        private void ShowAction(string action)
        {
            _selectedAction = action;
        }

        private void HideAction()
        {
            _selectedAction = null;
        }
    }
}
